# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 00a380e11cbdaa7004d8d8dc026fb2ca3d7bcd89347f9637a58003e620766d061afae47c94c23b8ef27294f9e3ddd987c5fe9e907a3194fa359bd152c31b092b

test:
  secret_key_base: 572d49ea74767246b929cd5f486993d7b58cbf3879da2d7d9c389deb89e525582678521f9dabd1d31f05bbfd7644057393ac47e57302d0c459a7aabbacd392ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
